version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: forum_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: forum
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d forum"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - forum_network

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forum_nextjs
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/forum
      - NODE_ENV=development
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-key-change-this-in-production
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - forum_network
    # Enable debugging
    # command: npm run dev -- --inspect=0.0.0.0:9229

networks:
  forum_network:
    driver: bridge

volumes:
  postgres_data:
