version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: forum_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: forum
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - forum_network

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forum_nextjs
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/forum
      - NODE_ENV=development
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - forum_network

networks:
  forum_network:
    driver: bridge

volumes:
  postgres_data:
